version = 1

# Contributor identities and history are maintained by GitHub:
# https://github.com/lapiz-rs/lapiz/graphs/contributors

[[annotations]]
path = [
  ".cargo/**",
  ".github/**",
  "assets/**",
  "crates/**",
  "default_config/**",
  "deny.toml",
  "docs/**",

  ".gitignore",
  ".node-version",
  "about.toml",
  "about.hbs",
  "Cargo.toml",
  "Cargo.lock",
  "justfile",
  "README.md",
  "rustfmt.toml",
  "rust-toolchain.toml",
]
SPDX-FileCopyrightText = "Contributors to Lapiz"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
  "crates/lapiz_abr/**",
  "crates/lapiz_abr_derive/**",
  "crates/lapiz_lazuli/**",
]
SPDX-FileCopyrightText = "Contributors to Lapiz"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "crates/lapiz_render/src/shaders/hash.wesl"
SPDX-FileCopyrightText = [
  "2014 David Hoskins",
  "Contributors to Lapiz",
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "crates/lapiz_render/src/shaders/math.wesl"
SPDX-FileCopyrightText = [
  "2015 Inigo Quilez",
  "Contributors to Lapiz",
]
SPDX-License-Identifier = "GPL-3.0-or-later AND MIT"

[[annotations]]
path = "docs/readme/main.png"
SPDX-FileCopyrightText = [
  "Contributors to Lapiz",
  "Dariusz Duchiewicz",
]
SPDX-License-Identifier = "GPL-3.0-or-later AND LicenseRef-Pexels"
