[package]
name = "cyancia_actions"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
cyancia_assets.workspace = true
cyancia_canvas.workspace = true
cyancia_image.workspace = true
cyancia_input.workspace = true
cyancia_render.workspace = true
cyancia_runtime.workspace = true
cyancia_tools.workspace = true
cyancia_undo.workspace = true
cyancia_utils.workspace = true
futures.workspace = true
iced_core.workspace = true
iced_runtime.workspace = true
log.workspace = true
rfd.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
