[package]
name = "lapiz_about"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
iced_core.workspace = true
iced_runtime.workspace = true
lapiz_i18n.workspace = true
lapiz_runtime.workspace = true
lapiz_widgets.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
